version: '3.9'
services :
  db:
    image: postgres:10-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: fabricio
      POSTGRES_PASSWORD: fabricio
      POSTGRES_DB: sw-planet
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080